name: slang
description: Localization / Internationalization (i18n) solution. Use JSON, YAML, CSV, or ARB files to create typesafe translations via source generation.
version: 3.30.1
repository: https://github.com/slang-i18n/slang
topics:
  - i18n
  - localization
  - internationalization
  - translation
screenshots:
  - description: The slang logo.
    path: resources/icon.png
funding:
  - https://github.com/sponsors/Tienisto/

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  collection: ^1.15.0
  csv: ^5.0.1
  json2yaml: ^3.0.0
  watcher: ^1.0.2
  yaml: ^3.1.0

dev_dependencies:
  expect_error: ^1.0.7
  lints: ^2.0.0
  test: ^1.21.0
